### ISSUE TITLE
Error reading the XML-file

### ISSUE THREAD

**Issue by AMBE1203** [Ashampoo/xmpcore#8]
My code:
        val path = getFirstSavedImage(this)

        path?.let {
            Log.e(TAG, it)

            val myBitmap = BitmapFactory.decodeFile(it)

            img.setImageBitmap(myBitmap)

            val bytes = readFileAsByteArray(it)

            if (bytes == null) {
               Log.e(TAG, "File could not be read:")
                return
            }

            val xmp = bytes.decodeToString()
            val xmpMeta = XMPMetaFactory.parseFromString(xmp)
            Log.e(TAG, "xmpMeta: $xmpMeta")
            
        }
but it got error : Error reading the XML-file

**Comment by StefanOltmann** [comment]
Please ensure that the XMP is provided in a text format. The current input appears to be a byte array representing an entire image file. To proceed, you can utilize the tool available at https://github.com/Ashampoo/kim in order to extract the embedded XMP data from the image.

**Comment by AMBE1203** [comment]
> Please ensure that the XMP is provided in a text format. The current input appears to be a byte array representing an entire image file. To proceed, you can utilize the tool available at https://github.com/Ashampoo/kim in order to extract the embedded XMP data from the image.
> 
> A XMP text looks like this:
> 
> ```
>             <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
>               <rdf:Description rdf:about=""
>                   xmlns:dc="http://purl.org/dc/elements/1.1/"
>                   xmlns:exif="http://ns.adobe.com/exif/1.0/"
>                   xmlns:xmp="http://ns.adobe.com/xap/1.0/"
>                 exif:DateTimeOriginal="1980-03-15T08:15:30"
>                 exif:GPSLatitude="53,13.1635N"
>                 exif:GPSLongitude="8,14.3797E"
>                 exif:GPSVersionID="2.3.0.0"
>                 xmp:Rating="2">
>                 <dc:subject>
>                   <rdf:Bag>
>                     <rdf:li>fox</rdf:li>
>                     <rdf:li>swiper</rdf:li>
>                   </rdf:Bag>
>                 </dc:subject>
>               </rdf:Description>
>             </rdf:RDF>
> ```

Thanks for your help, but when I use your suggestion I can't get the XMP data from the image.

            val bytes = readFileAsByteArray(it)

            if (bytes == null) {
               Log.e(TAG, "File could not be read:")
                return
            }

            val metadata = Kim.readMetadata(bytes)
            metadata?.xmp?.let { xmp ->
                val xmpMeta = XMPMetaFactory.parseFromString(xmp)
            }

            Log.e(TAG, "xmpMeta: ${metadata?.xmp}")

**Comment by StefanOltmann** [comment]
Does your image actually have XMP data?
You could check that with [ExifTool](https://exiftool.org/).

Can you share the file in question?

**Comment by AMBE1203** [comment]
my file: 
![20190313_203942](https://github.com/Ashampoo/xmpcore/assets/31823215/4c102819-f7c2-4576-8d0d-ee793ca34cd8)

**Comment by StefanOltmann** [comment]
The file you attached doesn't have any metadata at all.

<img width="619" alt="grafik" src="https://github.com/Ashampoo/xmpcore/assets/9299303/88474dc7-ea2c-4fa0-a61d-954a38eeea99">

**Comment by AMBE1203** [comment]
Thanks you very much!

**Comment by AMBE1203** [comment]
@StefanOltmann  i want to write xmp data into my file, please suggest me to solve this problem.
thank you!

**Comment by StefanOltmann** [comment]
Here you find samples how to create XMP data (as a String): https://github.com/Ashampoo/xmpcore/blob/main/src/commonTest/kotlin/com/ashampoo/xmp/WriteXmpTest.kt

With Kim you can use `JpegRewriter.updateXmpXml()` to include/replace the XMP part of your JPEG.

This is if you already have an XMP string (like from an sidecar) that you want to embed into the file.

If you want to update the rating (XMP-exlusive value) for example Kim has an easy API for that:
```
val bytes: ByteArray = loadBytes()

val newBytes = Kim.update(
    bytes = bytes,
    updates = setOf(
        MetadataUpdate.Rating(PhotoRating.THREE_STARS)
    )
)
```

**Comment by AMBE1203** [comment]
> Here you find samples how to create XMP data (as a String): https://github.com/Ashampoo/xmpcore/blob/main/src/commonTest/kotlin/com/ashampoo/xmp/WriteXmpTest.kt
> 
> With Kim you can use `JpegRewriter.updateXmpXml()` to include/replace the XMP part of your JPEG.
> 
> This is if you already have an XMP string (like from an sidecar) that you want to embed into the file.
> 
> If you want to update the rating (XMP-exlusive value) for example Kim has an easy API for that:
> 
> ```
> val bytes: ByteArray = loadBytes()
> 
> val newBytes = Kim.update(
>     bytes = bytes,
>     updates = setOf(
>         MetadataUpdate.Rating(PhotoRating.THREE_STARS)
>     )
> )
> ```

In Kim,   fun updateXmpXml(byteReader: ByteReader, byteWriter: ByteWriter, xmpXml: String), 
What is byteReader? and What is byteWriter

**Comment by AMBE1203** [comment]
> an use `JpegRewriter.updateXmpXml()`

I used JpegRewriter.updateXmpXml(), but it canot replace  the XMP data to my JPEG

**Comment by StefanOltmann** [comment]
> I used JpegRewriter.updateXmpXml(), but it canot replace the XMP data to my JPEG

It can.

**Comment by AMBE1203** [comment]
@StefanOltmann . Here is my code, it doesn't seem to update the metadata in the original image

            val bytes = readFileAsByteArray(it)

            if (bytes == null) {
                Log.e(TAG, "File could not be read:")
                return
            }
            
            val metadata = Kim.readMetadata(bytes)
            if (metadata?.xmp != null) {
                Log.e(TAG, "111111: ${metadata.xmp}")


            } else {
                val newMetaDat = createNewXmp()
                val byteReader = ByteArrayByteReader(bytes)
                val actualXmp =
                    XMPMetaFactory.serializeToString(newMetaDat, xmpSerializeOptionsCompact)
                val byteWriter = ByteArrayByteWriter()
                JpegRewriter.updateXmpXml(byteReader, byteWriter = byteWriter, actualXmp)
            }

**Comment by StefanOltmann** [comment]
The modified byte segments are now encapsulated within the `ByteArrayByteWriter` object. To obtain them, simply invoke the `toByteArray()` method on this object. You'll need to substitute the original bytes of your image with this new ByteArray.

**Comment by AMBE1203** [comment]
Thank you.
When i add 
    implementation 'com.ashampoo:xmpcore:0.1.5'
    implementation 'com.ashampoo:kim:0.5.1' 
in build.gradle (app), but has error:
The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'com.android.build.api.attributes.ProductFlavor:enviroment' with value 'development', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.3.1'. However we cannot choose between the following variants of com.ashampoo:xmpcore:0.1.5:

please help me fix it

**Comment by StefanOltmann** [comment]
Try adding only `kim` as `kim` already depends on `xmpcore`.

**Comment by AMBE1203** [comment]
when i add only Kim in project android(java) the above error still occurs

**Comment by StefanOltmann** [comment]
Okay, I need to find some time to look into this. Thank you for reporting.

**Comment by AMBE1203** [comment]
@StefanOltmann  
Can I update xmp metadata for images in png format?
Using PngWriter.writeImage() ???

**Comment by StefanOltmann** [comment]
Yes, you can. Take a look at https://github.com/Ashampoo/kim/blob/main/src/commonTest/kotlin/com/ashampoo/kim/format/png/PngWriterTest.kt
